"""add carts and cart_items tables

Revision ID: 21bfabb87cf6
Revises: 9f4e9231e14b
Create Date: 2026-08-29 02:13:32.820780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bfabb87cf6'
down_revision: Union[str, None] = '9f4e9231e14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_tenant_id'), 'carts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_items_tenant_id'), 'cart_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # RLS Policies for carts
    op.execute("ALTER TABLE carts ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE carts FORCE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY select_policy ON carts FOR SELECT USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    op.execute("CREATE POLICY insert_policy ON carts FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    op.execute("CREATE POLICY update_policy ON carts FOR UPDATE USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    op.execute("CREATE POLICY delete_policy ON carts FOR DELETE USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")

    # RLS Policies for cart_items
    op.execute("ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE cart_items FORCE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY select_policy ON cart_items FOR SELECT USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    op.execute("CREATE POLICY insert_policy ON cart_items FOR INSERT WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    op.execute("CREATE POLICY update_policy ON cart_items FOR UPDATE USING (tenant_id = current_setting('app.current_tenant', true)::uuid) WITH CHECK (tenant_id = current_setting('app.current_tenant', true)::uuid);")
    op.execute("CREATE POLICY delete_policy ON cart_items FOR DELETE USING (tenant_id = current_setting('app.current_tenant', true)::uuid);")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP POLICY IF EXISTS select_policy ON cart_items;")
    op.execute("DROP POLICY IF EXISTS insert_policy ON cart_items;")
    op.execute("DROP POLICY IF EXISTS update_policy ON cart_items;")
    op.execute("DROP POLICY IF EXISTS delete_policy ON cart_items;")
    op.execute("ALTER TABLE cart_items DISABLE ROW LEVEL SECURITY;")

    op.execute("DROP POLICY IF EXISTS select_policy ON carts;")
    op.execute("DROP POLICY IF EXISTS insert_policy ON carts;")
    op.execute("DROP POLICY IF EXISTS update_policy ON carts;")
    op.execute("DROP POLICY IF EXISTS delete_policy ON carts;")
    op.execute("ALTER TABLE carts DISABLE ROW LEVEL SECURITY;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_tenant_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_tenant_id'), table_name='carts')
    op.drop_table('carts')
    # ### end Alembic commands ###
