"""Add growth models

Revision ID: 40a745594725
Revises: 763c3993a48f
Create Date: 2026-08-31 00:29:33.752126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40a745594725'
down_revision: Union[str, None] = '763c3993a48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_experiment_name')
    )
    op.create_table('experiment_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Enable RLS
    op.execute("ALTER TABLE analytics_events ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE experiments ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE experiment_participants ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE recommendations ENABLE ROW LEVEL SECURITY")

    # Create policies
    op.execute("CREATE POLICY tenant_isolation_policy ON analytics_events USING (tenant_id = current_setting('app.current_tenant', true)::uuid)")
    op.execute("CREATE POLICY tenant_isolation_policy ON experiments USING (tenant_id = current_setting('app.current_tenant', true)::uuid)")
    op.execute("CREATE POLICY tenant_isolation_policy ON experiment_participants USING (tenant_id = current_setting('app.current_tenant', true)::uuid)")
    op.execute("CREATE POLICY tenant_isolation_policy ON recommendations USING (tenant_id = current_setting('app.current_tenant', true)::uuid)")


def downgrade() -> None:
    """Downgrade schema."""
    # Drop policies
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON analytics_events")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON experiments")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON experiment_participants")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON recommendations")
    
    # Disable RLS
    op.execute("ALTER TABLE analytics_events DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE experiments DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE experiment_participants DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE recommendations DISABLE ROW LEVEL SECURITY")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('experiment_participants')
    op.drop_table('experiments')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
