"""Add policies table

Revision ID: 4f821d710497
Revises: 71487ee8454b
Create Date: 2026-08-29 18:51:27.441733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f821d710497'
down_revision: Union[str, None] = '71487ee8454b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_policy_tenant_name')
    )
    op.create_index('ix_policies_rules', 'policies', ['rules'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    
    # Enable RLS
    op.execute("ALTER TABLE policies ENABLE ROW LEVEL SECURITY;")
    
    # Create RLS policies with NULLIF casting
    op.execute("CREATE POLICY select_policy ON policies FOR SELECT USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")
    op.execute("CREATE POLICY insert_policy ON policies FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")
    op.execute("CREATE POLICY update_policy ON policies FOR UPDATE USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")
    op.execute("CREATE POLICY delete_policy ON policies FOR DELETE USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")
    
    # Grant permissions to rg_app
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON policies TO rg_app;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("REVOKE ALL PRIVILEGES ON policies FROM rg_app;")
    
    op.execute("DROP POLICY IF EXISTS select_policy ON policies;")
    op.execute("DROP POLICY IF EXISTS insert_policy ON policies;")
    op.execute("DROP POLICY IF EXISTS update_policy ON policies;")
    op.execute("DROP POLICY IF EXISTS delete_policy ON policies;")
    
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_index('ix_policies_rules', table_name='policies', postgresql_using='gin')
    op.drop_table('policies')
    # ### end Alembic commands ###
