"""add_ai_session_models

Revision ID: bef947f175d3
Revises: 4f821d710497
Create Date: 2026-08-30 23:39:37.519854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bef947f175d3'
down_revision: Union[str, None] = '4f821d710497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False),
    sa.Column('experiment_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('decision_type', sa.String(length=255), nullable=False),
    sa.Column('decision_summary', sa.String(), nullable=False),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['ai_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    RLS_TABLES = [
        "ai_sessions",
        "agent_decisions",
        "agent_tool_calls",
        "ai_messages"
    ]
    
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY;")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY;")
        op.execute(f"CREATE POLICY select_policy ON {table} FOR SELECT USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")
        op.execute(f"CREATE POLICY insert_policy ON {table} FOR INSERT WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")
        op.execute(f"CREATE POLICY update_policy ON {table} FOR UPDATE USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid) WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")
        op.execute(f"CREATE POLICY delete_policy ON {table} FOR DELETE USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);")


def downgrade() -> None:
    """Downgrade schema."""
    RLS_TABLES = [
        "ai_sessions",
        "agent_decisions",
        "agent_tool_calls",
        "ai_messages"
    ]
    
    for table in RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS select_policy ON {table};")
        op.execute(f"DROP POLICY IF EXISTS insert_policy ON {table};")
        op.execute(f"DROP POLICY IF EXISTS update_policy ON {table};")
        op.execute(f"DROP POLICY IF EXISTS delete_policy ON {table};")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_messages')
    op.drop_table('agent_tool_calls')
    op.drop_table('agent_decisions')
    op.drop_table('ai_sessions')
    # ### end Alembic commands ###
